export const CURRENT_LOCATION = "CURRENT_LOCATION";
export const ORIGIN = "ORIGIN";
export const DESTINATION = "DESTINATION";

export const MAP_BOX_ROUTE = "MAP_BOX_ROUTE";
export const MAP_QUEST_ROUTE = "MAP_QUEST_ROUTE";
export const T_MAP_ROUTE_DEFAULT = "T_MAP_ROUTE_DEFAULT";
export const T_MAP_ROUTE_BIG_ROAD = "T_MAP_ROUTE_BIG_ROAD";
export const T_MAP_ROUTE_SHORTEST = "T_MAP_ROUTE_SHORTEST";
export const T_MAP_ROUTE_EXCEPT_STAIRS = "T_MAP_ROUTE_EXCEPT_STAIRS";

export const LOADING_COVID_STATUS = "LOADING_COVID_STATUS";
export const LOADING_CURRENT_LOCATION = "LOADING_CURRENT_LOCATION";
export const LOADING_ROUTES = "LOADING_ROUTES";

export const DANGER_LOCATION = "DANGER_LOCATION";

export const NAVIGATION_DATA = "NAVIGATION_DATA";

export const CHANGE_MAP_MODE = "CHANGE_MAP_MODE";

export const COVID_STAUS_DATA = "COVID_STATUS_DATA";

export const CHECK_START = "CHECK_START";
export const CHECK_FINISH = "CHECK_FINISH";
